name: flutter_ios_voip_kit

description: One-to-one video call using CallKit and PushKit with flutter ios app.

version: 0.0.7

homepage: https://github.com/masashi-sutou/flutter_ios_voip_kit

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: netkeepingblog.flutter_ios_voip_kit
        pluginClass: FlutterIOSVoIPKitPlugin
      ios:
        pluginClass: FlutterIOSVoIPKitPlugin

